name: Paladin Counsel
favicon: null
layout_spectrum: 0.86015
typography_spectrum: 0.87005
title: Paladin-Counsel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f5b00'
    - '#fefffc'
    - '#bda557'
    - '#ac8d35'
    - '#decea2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
