name: Paladin-Counsel
favicon: null
layout_spectrum: 0.7740577440708876
typography_spectrum: 0.2718147016130388
title: Paladin-Counsel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9051179599482566
  lightness: 0.07024068641476333
  saturation: 0.678565603448078
  rhythmicContrast: 0.31631116988137364
purpose: []
