title: Paladin-Counsel.com
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5625
  rhythmicContrast: 0.75
  brandColors:
    - '#7f5b00'
    - '#fefffc'
    - '#bda557'
    - '#ac8d35'
    - '#decea2'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Paladin Counsel
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.87005
layout_spectrum: 0.1735589
